defaults: &defaults
  close_time: '2016-05-04 23:30:00 +0200' #4 May 2015, 23:30 CEST

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  google_analitics: UA-60389282-1
